# https: yes        # options: no, yes, force
# http_port: 8280
# https_port: 8443
# index_file: index1.html
# cert: cert.pem
# key: key.pem


port: 8280

https:
  force: false
  port: 8443
  cert: cert.pem
  key: key.pem


index_file: index1.html
allow_list_content: true
